title: Yu Zhou
logo: 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

header_pages:
  - index.md
  - cv.md
  - photography.md

# Use this line to include the custom header
include:
  - _includes/header.html
